version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: dkp-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: dkp-frontend
    ports:
      - "8089:80"
    depends_on:
      - backend
    restart: always
