import { ROUTE_ACCESS } from '../../app/rbac.js'

export const navItems = [
  {
    to: '/dashboard',
    label: 'Dashboard',
    iconName: 'LayoutDashboard',
    roles: ROUTE_ACCESS.dashboard,
  },
  {
    to: '/submit-paper',
    label: 'Submission Wizard',
    roles: ROUTE_ACCESS.uploadDocument,
  },
  {
    to: '/repository',
    label: 'Repository',
    roles: ROUTE_ACCESS.repository,
  },
  {
    to: '/library',
    label: 'Library Hub',
    iconName: 'BookOpen',
    roles: ROUTE_ACCESS.library,
  },
  {
    to: '/library/upload',
    label: 'Upload Assets',
    iconName: 'UploadCloud',
    roles: ROUTE_ACCESS.libraryUpload,
  },
  {
    to: '/library/bookmarks',
    label: 'My Favorites',
    iconName: 'Bookmark',
    roles: ROUTE_ACCESS.libraryBookmarks,
  },
  {
    to: '/library/analytics',
    label: 'Insights',
    iconName: 'BarChart3',
    roles: ROUTE_ACCESS.libraryAnalytics,
  },
  {
    to: '/library/librarian',
    label: 'Librarian Hub',
    iconName: 'ClipboardList',
    roles: ROUTE_ACCESS.librarianHub,
  },
  {
    to: '/library/catalog',
    label: 'Catalog Search',
    iconName: 'Search',
    roles: ROUTE_ACCESS.libraryCatalogSearch,
  },
  {
    to: '/library/circulation',
    label: 'Circulation',
    iconName: 'Repeat',
    roles: ROUTE_ACCESS.libraryCirculation,
  },
  {
    to: '/library/due-tracking',
    label: 'Due Tracker',
    iconName: 'Clock',
    roles: ROUTE_ACCESS.libraryDueTracking,
  },
  {
    to: '/library/fines',
    label: 'Fine Management',
    iconName: 'DollarSign',
    roles: ROUTE_ACCESS.libraryFines,
  },
  {
    to: '/library/holds',
    label: 'Hold Requests',
    iconName: 'BookmarkCheck',
    roles: ROUTE_ACCESS.libraryHolds,
  },
  {
    to: '/library/wishlist',
    label: 'Wishlist',
    iconName: 'Heart',
    roles: ROUTE_ACCESS.libraryWishlist,
  },
  {
    to: '/library/history',
    label: 'Borrowing History',
    iconName: 'History',
    roles: ROUTE_ACCESS.libraryHistory,
  },
  {
    to: '/library/scan',
    label: 'Scan Station',
    iconName: 'ScanLine',
    roles: ROUTE_ACCESS.libraryScan,
  },
  {
    to: '/library/catalog-crud',
    label: 'Catalog Manager',
    iconName: 'FolderPlus',
    roles: ROUTE_ACCESS.libraryCatalogCrud,
  },
  {
    to: '/library/bulk-import',
    label: 'Bulk Import',
    iconName: 'FileSpreadsheet',
    roles: ROUTE_ACCESS.libraryBulkImport,
  },
  {
    to: '/library/reports',
    label: 'Reports',
    iconName: 'BarChart3',
    roles: ROUTE_ACCESS.libraryReports,
  },
  {
    to: '/library/settings',
    label: 'Settings',
    iconName: 'Settings2',
    roles: ROUTE_ACCESS.librarySettings,
  },
  {
    to: '/student-projects',
    label: 'Project Showcase',
    roles: ROUTE_ACCESS.studentProjectShowcase,
  },
  {
    to: '/all-uploads',
    label: 'Global Records',
    iconName: 'Globe2',
    roles: ROUTE_ACCESS.allUploads,
  },
  {
    to: '/review-queue',
    label: 'Review Lab',
    iconName: 'ClipboardCheck',
    roles: ROUTE_ACCESS.reviewQueue,
  },
  {
    to: '/viewer/sample-doc',
    label: 'Viewer',
    roles: ROUTE_ACCESS.viewer,
  },
  {
    to: '/admin',
    label: 'System Admin',
    iconName: 'ShieldCheck',
    roles: ROUTE_ACCESS.admin,
  },
]
